### PR TITLE
Fix peto to remove deprecation

### PR DESCRIPTION
**Pull request by m5ka**
The word `peto` is listed as "deprecated by the creator" but this is untrue and unverifiable, particularly as I am the creator and did not ever deprecate it. It is still a word I personally use to this day, and I still see others use it across various toki pona communities and it remains a useful nimi sin in terms of its semantics.

– jan kiwa

### CODE REVIEW

**Comment by tbodt** [comment]
sona li tan kulupu kasi. ona li toki e ni: ona li pali e nimi li wile pini e ona. sina sona ala sona e ona?

**Comment by m5ka** [comment]
> Reference i

kulupu kasi admitted in 2017 that their participation in the creation of the word was low, amounting to encouragement only. I was the person who actively created, adopted and spread the word in the early period.

kulupu kasi since 2017 became very vehemently anti-nimi sin generally, hence this stance. however in this case, they had no authority to request that the word not be used and these messages in ma pona happened without consulting me at all.

my stance has always been that I encourage peto's use.

**Comment by KelseyHigham** [comment]
here's that 2017 kulupu kasi statement:
https://discord.com/channels/301377942062366741/301377942062366741/396984495477227524

**Comment by tbodt** [comment]
mi toki tawa kulupu kasi li kute e ni: sina tu li pali e nimi. tenpo li tawa la sina tu li kama pilin pi ante mute lon ona, a a.

mi la lon li ni: jan mute ala li kepeken nimi, jan o kepeken ala tan ni. taso lipu Linku kin li toki a e ni, li wile lon ala e toki namako ni: jan pali nimi li wile pini e ona tan ni.

ni la ante ni li pona

**Pull request merged**
